from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from app.rag.domain import Chunk, Evidence, Scope, Task


class RagStore(Protocol):
    """Atomic persistence commands; each completes before a provider call begins."""

    async def index(self, scope: Scope, retry_key: str | None = None) -> dict[str, Any]: ...
    async def ask(self, scope: Scope, key: str, question: str) -> dict[str, Any]: ...
    async def question(self, scope: Scope, question_id: UUID) -> dict[str, Any]: ...
    async def history(self, scope: Scope) -> list[dict[str, Any]]: ...
    async def cancel(self, scope: Scope, question_id: UUID) -> dict[str, Any]: ...
    async def claim_index(self) -> Task | None: ...
    async def prepare(self, task: Task, chunks: list[Chunk]) -> bool: ...
    async def units(self, task: Task) -> list[tuple[int, str]] | None: ...
    async def pending(self, task: Task) -> list[Evidence]: ...
    async def save_vectors(
        self, task: Task, sources: list[Evidence], vectors: list[list[float]]
    ) -> bool: ...
    async def finish_index(self, task: Task) -> None: ...
    async def fail_index(self, task: Task, failure_code: str) -> None: ...
    async def claim_question(self) -> Task | None: ...
    async def active(self, task: Task) -> bool: ...
    async def retrieve(self, task: Task, vector: list[float]) -> list[Evidence]: ...
    async def finish_question(
        self, task: Task, answer: dict[str, Any], usage: dict[str, Any]
    ) -> None: ...
    async def fail_question(self, task: Task, failure_code: str) -> None: ...


class Embeddings(Protocol):
    async def embed(self, texts: list[str], *, query: bool = False) -> list[list[float]]: ...


class AnswerModel(Protocol):
    async def answer(
        self, question: str, sources: list[Evidence]
    ) -> tuple[dict[str, Any], dict[str, Any]]: ...
